name: Deploy

on:
  push:
    branches:
      - main

env:
  LAMBDA_FUNCTION_NAME: "basic-auth"

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout github code
        uses: actions/checkout@v3
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Clean install node packages
        env:
          CI: true
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Package code
        run: |
          zip -r deploy.zip ./ -x "./src/*" "tsconfig.json"
          echo "zip created"
      - name: Deploy to lambda
        run: |
          aws lambda update-function-code --function-name=$LAMBDA_FUNCTION_NAME --zip-file=fileb://deploy.zip